### ISSUE TITLE
Page break doesn't reflow when removing the top line with backspace

### ISSUE THREAD

**Issue by simong** [ether/ep_page_view#14]
We're seeing some strange reflowing behaviour when removing the first line after a page break (with backspace if it matters). 

In the screencast you can see that the page break is removed, but it should just move the page break lower right?
http://screencast.com/t/mgYOInoois1

**Comment by JohnMcLear** [comment]
Confirmed.  A bounty would help me fix this sooner :)

**Comment by JohnMcLear** [comment]
Done https://github.com/ether/ep_page_view/commit/a9100e338295471717255a8cd761c808292c9ec6
