### ISSUE TITLE
Page breaks in page view plugin

### ISSUE THREAD

**Issue by deepsaggas** [ether/ep_page_view#19]
Hi
Styling for manual page Breaks is different from Automatic Page Breaks.
Automatic Page Breaks('class = pageBreakComputed') look like a single line but Manual ones(class='pageBreak') look like a block.
Check pad : https://beta.etherpad.org/p/newpad and do switch on Page View and Page Breaks
Why is this done. Can I make both of them appear same, if yes, how?
Thanks!
![page break issue](https://cloud.githubusercontent.com/assets/5969210/6141703/4d941e3e-b1cf-11e4-8bd6-edae6a70449b.png)

**Comment by JohnMcLear** [comment]
This is a bug
