### ISSUE TITLE
Green Background on mozilla

### ISSUE THREAD

**Issue by Billaboong** [ether/ep_page_view#32]
Hallo 
From the link : [https://beta.etherpad.org/p/beta](https://beta.etherpad.org/p/beta) there is a green background when using mozilla.

How can I change that color?

**Comment by JohnMcLear** [comment]
https://github.com/ether/ep_page_view/blob/master/static/css/iframe.css#L129 lol wtf.

**Comment by JohnMcLear** [comment]
Fixed and pushed.

**Comment by Billaboong** [comment]
Thanks @JohnMcLear  It has worked
